---
- name: Ensure control system is configured correctly
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - common

- name: Remove from NTP server list if needed
  hosts: ucs
  connection: local
  gather_facts: no
  vars_files:
    - vars/svars.yml
    - vars/default.yml

  tasks:
  - name: Ensure NTP server is removed
    cisco_ucs_ntp:
      name: "{{ntp_server}}"
      descr: Ansible managed NTP
      state: absent
      ucs_ip: "{{ucs_ip}}"
      ucs_username: "{{ucs_username}}"
      ucs_password: "{{ucs_password}}"
