---
- name: Ensure desired power state
  hosts: ucs
  connection: local
  gather_facts: no
  vars:
    - desired_power_state: on
  vars_files:
    - vars/svars.yml

  tasks:
  - name: Ensure blades/chassis power state
    cisco_ucs_power:
      chassis_id: "1"
      blade_id: "1"
      state: "{{ desired_power_state }}"
      ucs_ip: "{{ucs_ip}}"
      ucs_username: "{{ucs_username}}"
      ucs_password: "{{ucs_password}}"
