---
- name: Ensure control system is configured correctly
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - common

- name: Ensure timezone is configured
  hosts: ucs
  connection: local
  gather_facts: no
  vars_files:
    - vars/svars.yml
    - vars/default.yml

  tasks:
  - name: Ensure timezone is specified
    ucs_timezone:
      description: Ansible managed timezone
      state: present
      timezone: "{{ ucs_timezone }}"
      hostname: "{{ucs_ip}}"
      username: "{{ucs_username}}"
      password: "{{ucs_password}}"
